model_config: "configs/models/cnn.yaml"
dataset_config: "configs/datasets/cifar10.yaml"

seed: 42
device: "cuda"

# 组合损失函数配置示例
loss:
  type: "combined"
  weight: 1.0
  losses:
    - type: "cross_entropy"
      reduction: "mean"
      weight: 1.0
    - type: "l1"
      reduction: "mean"
      weight: 0.5

training:
  epochs: 50
  optimizer:
    type: "adam"
    lr: 0.001
    weight_decay: 1e-5
  scheduler:
    type: "cosine"
    T_max: 50
    eta_min: 0.0001
  early_stopping:
    patience: 50
    min_delta: 0.001
    monitor: "loss"
    mode: "min"
  checkpoint:
    save_frequency: 5  # 每5个epoch保存一次权重

# 钩子配置
hooks:
  - type: "TimeTrackingHook"
    name: "training_timer"
    frequency: 1 