model_config: "configs/models/cnn.yaml"
dataset_config: "configs/datasets/cifar10.yaml"

seed: 42
device: "cuda"
output_dir: "checkpoints/default"
log_dir: "logs/default"

training:
  epochs: 50
  optimizer:
    type: "adam"
    lr: 0.001
    weight_decay: 1e-5
  scheduler:
    type: "cosine"
    T_max: 50
    eta_min: 0.0001
  early_stopping:
    patience: 10
    min_delta: 0.001 