dataset:
  type: "cifar10"
  data_dir: "data/cifar10"
  batch_size: 64
  num_workers: 4
  transforms:
    resize: [32, 32]
    normalize:
      mean: [0.4914, 0.4822, 0.4465]
      std: [0.2023, 0.1994, 0.2010] 